### ISSUE TITLE
Refactoring 1

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#19]
Gather ideas for refactoring in this issue. Once it's 'full', we'll change them all at once.

**Comment by Stoeoef** [comment]
* baseeffectlist.py: 
  * remove lambdas
  * rename "Ith"-methods ("insertIth"...)
  * "add" -> 'add' , "remove" -> 'remove'

* match.py:
  * `revealNewInformation` -> replace with `newInformationRevealed`

**Comment by MartinAltmayer** [comment]
actions.add has a useless first argument

**Comment by MartinAltmayer** [comment]
Rename CombatRewardType -> RewardType. While the player gets rewards only after a combat, they are now handled separately.

**Comment by MartinAltmayer** [comment]
Rename endofturnview.py -> rewardsview.py

**Comment by MartinAltmayer** [comment]
The GraphicsItems of playerarea are now used in various places. Maybe we should create one module that contains items for cards, skills, units etc and use these in all places. Also, the size of items is currently fixed in several different places.

**Comment by MartinAltmayer** [comment]
Most of this has either been done or is completely outdated.
