### ISSUE TITLE
Implement shopping options as effect

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#43]
Maybe we should implement effects like "Can buy spells", "Can recruit units".
Pros:
 * Players are reminded that they have the option to buy stuff
 * The decision which things can be bought is realised within `match.py` at the moment. I think it's cleaner to move this to the sites (Maybe a method `startInteraction(self, match, player)` in `SiteOnMap`

**Comment by MartinAltmayer** [comment]
The problem is that the user should already know what he can buy before he clicks on "Start interaction". I think we can expect him to know the rules in this place.
I agree with your second point, though: It should be the site which decides what things can be bought.

**Comment by Stoeoef** [comment]
So, to summarize: We'll try to implement effects like "Can buy XYZ" as a "invisible" effect which is not visible in the effect list. I suggest we wait until we've implemented a few cards to see if there are more invisible effects we don't know yet, and decide then how to implement this (maybe similar to the current effect queue, or explicit (if there are just a few of those effects)
