### ISSUE TITLE
Allow spending move points in state explore

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#45]
I could think of further improvements, e.g. always showing explorable tiles when in `State.movement`, to support the player where tiles can be explored and where they can't. Additionally, we'd get rid of `State.explore` .

**Comment by MartinAltmayer** [comment]
Yes, we should remove State.explore and simply let the user explore directly.

**Comment by Stoeoef** [comment]
Further improvement: We could display all possibly explorable tiles (thus, they're in the wedge form, they have enough adjacent explored tiles, there are still map tiles available ...) in a darker colour at any time. All adjacent, "really" explorable tiles would have a lighter colour.
