### ISSUE TITLE
Distinguish between "played" cards and "discarded" cards

### ISSUE THREAD

**Issue by MartinAltmayer** [MartinAltmayer/mageknight#61]
Cards played during a turn should not be put onto the discard pile until the end of the turn. This matters for example with the Long Night tactic. Also note that e.g. with Concentration the second card is "played", while with Improvisation the second card is "discarded".

**Comment by Stoeoef** [comment]
Time Bending will require this as well.

**Comment by MartinAltmayer** [comment]
Closed in a07a36657b4575d.  Commit comment contains wrong issue number.
