### ISSUE TITLE
Undoing doesn't set available actions properly

### ISSUE THREAD

**Issue by Stoeoef** [MartinAltmayer/mageknight#82]
Undoing "Start End of Turn" doesn't show "Start End of Turn" again. Undoing "Provoke marauding enemies" doesn't show the provoke option again.

**Comment by Stoeoef** [comment]
I think the issue is that the gui's buttons are connected to `Stack.undo`, but not to `AbstractMatch::undo` (which does update the buttons) . Actually, I'm not sure if `AbstractMatch::undo` and `redo` are called anywhere at all.
I'd suggest one of three fixes:
* calling `AbstractMatch::undo` instead of `Stack::undo` 
* emitting `buttonsChanged` whenever the state changes.
* calling `startEOTSequence` via `executePlayerAction` .
What are your thoughts?

**Comment by MartinAltmayer** [comment]
The GUI should call AbstractMatch.undo (this also saves the match). After this is fixed the startEOT and provokeMarauders issues should be fixed, too. All buttons (except for undo/redo) already use AbstractMatch.playerAction and thus executePlayerAction.

**Comment by Stoeoef** [comment]
Fixed with #85
